# Machine Learning Zoomcamp


## 1.7 Introduction to NumPy


Plan:

* Creating arrays
* Multi-dimensional arrays
* Randomly generated arrays
* Element-wise operations
    * Comparison operations
    * Logical operations
* Summarizing operations

In [2]:
# numpy 라이브러리를 불러옵니다. (숫자 배열 계산용)
# as np 는 앞으로 np.xxx 처럼 짧게 쓰기 위한 별명입니다.
import numpy as np


In [3]:
# np 가 제대로 불러와졌는지 확인합니다. (모듈 정보가 출력됩니다)
np


<module 'numpy' from 'E:\\IT_SPACES\\AI\\ZoomCamp\\ML\\.venv\\Lib\\site-packages\\numpy\\__init__.py'>

## Creating arrays


In [4]:
# 길이 10인 배열을 만들고, 모든 값을 0.0 으로 채웁니다.
np.zeros(10)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
# 길이 10인 배열을 만들고, 모든 값을 1.0 으로 채웁니다.
np.ones(10)


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
# 길이 10인 배열을 만들고, 모든 값을 2.5 로 채웁니다.
# 첫 인자: 길이(크기), 둘째 인자: 채울 값
np.full(10, 2.5)


array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [7]:
# 파이썬 리스트를 NumPy 배열로 변환합니다.
a = np.array([1, 2, 3, 5, 7, 12])
# 변수 a 를 출력해 배열 내용을 확인합니다.
a


array([ 1,  2,  3,  5,  7, 12])

In [8]:
# 인덱스 2 위치(세 번째 값, 원래 3)를 10 으로 바꿉니다.
# 인덱스는 0부터 시작합니다: a[0]=1, a[1]=2, a[2]=3 ...
a[2] = 10


In [9]:
# 값이 바뀌었는지 배열 전체를 다시 확인합니다.
a


array([ 1,  2, 10,  5,  7, 12])

In [10]:
# 3 이상 10 미만의 정수를 순서대로 만든 배열입니다. (3,4,5,6,7,8,9)
# 끝값 10 은 포함되지 않습니다. (파이썬 range 와 같음)
np.arange(3, 10)


array([3, 4, 5, 6, 7, 8, 9])

In [11]:
# 0 부터 100 까지를 같은 간격으로 나눈 숫자 11개를 만듭니다.
# (시작, 끝, 개수) → 0, 10, 20, ... , 100
np.linspace(0, 100, 11)


array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

## Multi-dimensional arrays


In [12]:
# 5행 2열(세로 5, 가로 2) 크기의 2차원 배열을 만들고 전부 0 으로 채웁니다.
# 인자를 튜플 (행, 열) 로 줍니다.
np.zeros((5, 2))


array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [13]:
# 3행 3열 행렬을 직접 만듭니다. 바깥 [] 가 행(row), 안쪽 [] 가 한 행의 값들입니다.
n = np.array([
    [1, 2, 3],  # 0번 행
    [4, 5, 6],  # 1번 행
    [7, 8, 9]   # 2번 행
])


In [14]:
# n[행, 열] 형식입니다. 0번 행, 1번 열의 값(원래 2)을 20 으로 바꿉니다.
n[0, 1] = 20


In [30]:
# 행렬 n 전체를 출력해 변경 결과를 확인합니다.
n


array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [15]:
# 2번 행 전체를 [1, 1, 1] 로 바꿉니다. (한 행을 통째로 교체)
n[2] = [1, 1, 1]


In [16]:
# 2번 행이 바뀌었는지 확인합니다.
n


array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [17]:
# : 는 "모든 행" 이라는 뜻입니다. 모든 행의 2번 열을 [0, 1, 2] 로 바꿉니다.
# 즉 열 하나를 통째로 교체합니다.
n[:, 2] = [0, 1, 2]


In [18]:
# 마지막 열이 바뀌었는지 확인합니다.
n


array([[ 1, 20,  0],
       [ 4,  5,  1],
       [ 1,  1,  2]])

## Randomly generated arrays


In [19]:
# seed(2): 난수 시작값을 고정합니다. 같은 seed 면 실행할 때마다 같은 난수가 나옵니다.
np.random.seed(2)
# 0~1 사이 난수로 5행 2열 배열을 만든 뒤, 100을 곱해 대략 0~100 범위로 키웁니다.
100 * np.random.rand(5, 2)


array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [22]:
# 난수 시드를 다시 2로 맞춥니다.
np.random.seed(2)
# 표준정규분포(평균 0, 분산 1)에서 뽑은 난수로 5행 2열 배열을 만듭니다.
# rand 와 달리 음수도 나올 수 있습니다.
np.random.randn(5, 2)


array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [23]:
# 난수 시드를 다시 2로 맞춥니다.
np.random.seed(2)
# 정수 난수를 만듭니다.
# low=0: 최솟값(포함), high=100: 최댓값(미포함), size=(5,2): 5행 2열
np.random.randint(low=0, high=100, size=(5, 2))


array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]], dtype=int32)

## Element-wise operations


In [24]:
# 0 이상 5 미만 정수 배열 [0, 1, 2, 3, 4] 를 만듭니다.
a = np.arange(5)
# 배열 a 를 확인합니다.
a


array([0, 1, 2, 3, 4])

In [25]:
# 원소마다(element-wise) 같은 계산을 한 번에 적용합니다.
# 1) a * 2  → 각 원소에 2를 곱함
# 2) 10 + ... → 각 원소에 10을 더함
# 3) (... ) ** 2 → 각 원소를 제곱
# 4) / 100 → 각 원소를 100으로 나눔
b = (10 + (a * 2)) ** 2 / 100


In [26]:
# 계산 결과 배열 b 를 확인합니다.
b


array([1.  , 1.44, 1.96, 2.56, 3.24])

In [27]:
# a 의 각 원소를 b 의 같은 위치 원소로 나눈 뒤, 전체에 10을 더합니다.
# (배열끼리 위치별로 연산)
a / b + 10


array([10.        , 10.69444444, 11.02040816, 11.171875  , 11.2345679 ])

## Comparison operations

In [28]:
# 비교에 쓸 배열 a 를 다시 확인합니다. [0, 1, 2, 3, 4]
a


array([0, 1, 2, 3, 4])

In [29]:
# a 의 각 원소가 2 이상인지 True/False 로 알려줍니다.
# 결과 예: [False, False, True, True, True]
a >= 2


array([False, False,  True,  True,  True])

In [30]:
# 비교 대상 배열 b 를 확인합니다.
b


array([1.  , 1.44, 1.96, 2.56, 3.24])

In [31]:
# a 와 b 를 같은 위치끼리 비교합니다. a 원소가 b 원소보다 크면 True
a > b

array([False, False,  True,  True,  True])

In [32]:
# 대괄호 안 조건이 True 인 위치의 a 값만 골라냅니다. (불리언 인덱싱 / 필터링)
# 즉 "b 보다 큰 a 의 원소들만" 남깁니다.
a[a > b]


array([2, 3, 4])

## Summarizing operations

In [33]:
# 요약 통계에 쓸 배열 a 를 확인합니다.
a


array([0, 1, 2, 3, 4])

In [34]:
# a 전체 원소의 표준편차(값이 평균에서 얼마나 퍼져 있는지)를 계산합니다.
a.std()


np.float64(1.4142135623730951)

In [35]:
# 행렬 n 에 들어 있는 모든 값 중 최솟값을 구합니다.
n.min()


np.int64(0)

### Next

Linear algebra refresher