# Machine Learning Zoomcamp

## 1.8 Linear algebra refresher

Plan:

* Vector operations
* Multiplication
    * Vector-vector multiplication
    * Matrix-vector multiplication
    * Matrix-matrix multiplication
* Identity matrix
* Inverse

In [72]:
# 넘파이 라이브러리를 불러옵니다. (숫자 배열·선형대수 연산용)
# as np 는 앞으로 np.xxx 처럼 짧게 쓰기 위한 별명입니다.
import numpy as np


## Vector operations

In [73]:
# 첫 번째 벡터 u를 생성합니다. (요소 4개)
u = np.array([2, 4, 5, 6])


In [74]:
# 벡터의 모든 요소에 스칼라 값(2)을 각각 곱합니다. (스칼라 곱셈)
2 * u


array([ 4,  8, 10, 12])

In [75]:
# 두 번째 벡터 v를 생성합니다. (u와 같이 요소 4개)
v = np.array([1, 0, 0, 2])


In [76]:
# 같은 위치의 요소끼리 더하는 벡터 덧셈을 수행합니다.
u + v


array([3, 4, 5, 8])

In [77]:
# 같은 위치의 요소끼리 곱하는 요소별(element-wise) 곱셈입니다. (내적과는 다릅니다)
u * v


array([ 2,  0,  0, 12])

## Multiplication

In [78]:
# 벡터 v의 길이(첫 번째 축 크기 = 요소 개수)를 확인합니다.
v.shape[0]


4

In [79]:
# 두 벡터 간의 곱셈(내적, dot product)을 직접 구현한 함수입니다.
def vector_vector_multiplication(u, v):
    # 두 벡터의 크기(차원)가 다르면 연산이 불가능하므로 오류를 냅니다.
    assert u.shape[0] == v.shape[0]

    # 벡터의 요소 개수(차원 크기)를 n에 저장합니다.
    n = u.shape[0]

    # 결과를 누적할 변수를 0.0으로 초기화합니다.
    result = 0.0

    # 0부터 n-1까지 각 위치의 요소에 접근합니다.
    for i in range(n):
        # u와 v의 i번째 요소를 곱한 뒤 결과에 누적합니다.
        result = result + u[i] * v[i]

    # 최종 내적 값을 반환합니다.
    return result


In [80]:
# 직접 만든 함수로 벡터 u와 v의 내적을 계산합니다.
vector_vector_multiplication(u, v)


14.0

In [81]:
# 넘파이에 내장된 내적 메서드(.dot)로 같은 결과를 확인합니다.
u.dot(v)


14

In [82]:
# 연산에 사용할 2차원 행렬 U를 정의합니다. (행 3개, 열 4개)
U = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1],
])


In [83]:
# 행렬 U의 모양(행 개수, 열 개수)을 확인합니다.
U.shape


(3, 4)

In [88]:
# 행렬과 벡터의 곱셈을 수행하는 함수를 정의합니다.
def matrix_vector_multiplication(U, v):
    # 행렬 U의 열 개수와 벡터 v의 요소 개수가 같아야 하므로 검증합니다.
    assert U.shape[1] == v.shape[0]

    # 행렬 U의 행 개수를 가져옵니다. (결과 벡터의 크기가 됩니다.)
    num_rows = U.shape[0]

    # 결과를 담을 1차원 배열을 0으로 초기화합니다.
    result = np.zeros(num_rows)

    # 행렬의 각 행을 순회합니다.
    for i in range(num_rows):
        # i번째 행과 벡터 v의 내적을 구해 결과의 i번째 자리에 넣습니다.
        result[i] = vector_vector_multiplication(U[i], v)

    # 최종 결과 벡터를 반환합니다.
    return result


In [89]:
# 직접 만든 함수로 행렬 U와 벡터 v를 곱합니다.
matrix_vector_multiplication(U, v)


array([14.,  5.,  5.])

In [90]:
# 넘파이 .dot 으로 같은 행렬-벡터 곱셈 결과를 확인합니다.
U.dot(v)

array([14,  5,  5])

In [91]:
# 연산에 사용할 두 번째 행렬 V를 정의합니다. (행 4개, 열 3개)
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1],
    [0, 2, 1],
    [2, 1, 0],
])


In [109]:
# 행렬과 행렬의 곱셈을 수행하는 함수를 정의합니다.
def matrix_matrix_multiplication(U, V):
    # 첫 번째 행렬의 열 개수와 두 번째 행렬의 행 개수가 같아야 하므로 검증합니다.
    assert U.shape[1] == V.shape[0]

    # 결과 행렬의 행 개수는 U의 행 개수, 열 개수는 V의 열 개수입니다.
    num_rows = U.shape[0]
    num_cols = V.shape[1]

    # 결과를 담을 2차원 행렬을 0으로 초기화합니다.
    result = np.zeros((num_rows, num_cols))

    # 두 번째 행렬 V의 각 열을 순회합니다.
    for i in range(num_cols):
        # V의 i번째 열을 가져옵니다.
        vi = V[:, i]
        # 행렬 U와 열 벡터 vi의 행렬-벡터 곱셈을 수행합니다.
        Uvi = matrix_vector_multiplication(U, vi)
        # 결과 행렬의 i번째 열에 계산된 벡터를 넣습니다.
        result[:, i] = Uvi

    # 최종 결과 행렬을 반환합니다.
    return result


In [110]:
# 직접 만든 함수로 행렬 U와 행렬 V를 곱합니다.
matrix_matrix_multiplication(U, V)


array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [23]:
# 넘파이 .dot 으로 같은 행렬-행렬 곱셈 결과를 확인합니다.
U.dot(V)


array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

## Identity matrix

In [112]:
# 크기가 3인 항등 행렬(Identity Matrix) I를 생성합니다.
# 주대각선은 1, 나머지는 0인 정사각 행렬입니다.
I = np.eye(3)

In [117]:
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [113]:
# 앞에서 만든 행렬 V를 다시 확인합니다. (4행 3열)
V


array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [115]:
# V에 항등 행렬 I를 곱하면 V 자신과 같아집니다. (항등 행렬의 성질)
V.dot(I)


array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

## Inverse

In [116]:
# 역행렬은 정사각 행렬만 가능하므로, V에서 앞의 3개 행만 골라 3x3 행렬 Vs를 만듭니다.
Vs = V[[0, 1, 2]]
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [118]:
# 넘파이(NumPy)의 선형대수 연산을 담당하는 서브패키지인 linalg(linear algebra의 약자)를 불러옵니다.
# linalg는 행렬 곱, 역행렬, 고유값 분해 등 선형대수학에 필요한 다양한 고급 수학 연산 기능을 제공합니다.

# inv() 함수는 inverse(역행렬)의 줄임말이며, 정사각 행렬을 인자로 받아 그 행렬의 역행렬을 계산합니다.
# 역행렬이란, 어떤 행렬에 곱했을 때 그 결과가 항등 행렬(주대각선이 1이고 나머지가 0인 행렬)이 되게 만드는 유일한 짝꿍 행렬을 뜻합니다.
# (주의: 행렬의 행과 열 크기가 완전히 같은 '정사각 행렬'이면서, 역행렬이 존재할 때만 계산할 수 있습니다.)
Vs_inv = np.linalg.inv(Vs)

# 계산된 역행렬 결과를 화면에 출력합니다.
Vs_inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [34]:
# 역행렬과 원래 행렬을 곱하면 항등 행렬(대각선 1, 나머지 0)이 되는지 확인합니다.
Vs_inv.dot(Vs)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Next 

Intro to Pandas